on: [push, pull_request]
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.14, 1.21.13, 1.22.10, 1.23.4]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5 # just in case ¯\_(ツ)_/¯
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Go Format
      run: gofmt -s -w . && git diff --exit-code
    - name: Go Vet
      run: go vet ./...
    - name: Test
      run: |
        go test ./... -v -race -coverprofile=coverage.txt -covermode=atomic 
        # go test -bench=.
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
